parameters:
- name: apiUrl
  type: string
- name: backendIdentifier
  type: string
- name: tenantId
  type: string
- name: clientId
  type: string

stages:
- stage: BuildPortal
  displayName: Build portal stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: windows-latest
      
    steps:
    - task: NodeTool@0  
      inputs:
        versionSpec: '16.x'
      displayName: 'Install Node.js'

    - script: |
        npm install && npm run build      
      env:
        REACT_APP_API_URL: ${{ parameters.apiUrl }}
        REACT_APP_BACKEND_IDENTIFIER: ${{ parameters.backendIdentifier }}
        REACT_APP_TENANT_ID: ${{ parameters.tenantId }}
        REACT_APP_CLIENT_ID: ${{ parameters.clientId }}
      displayName: 'Prepare binaries'            
     
      
    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-portal.zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-portal.zip
      artifact: drop-portal
      
    - upload: $(System.DefaultWorkingDirectory)/contentTypes.ps1
      artifact: drop-portal-ps