parameters:
- name: apiUrl
  type: string
- name: backendIdentifier
  type: string
- name: COMPANY_NAME
  type: string
- name: TENANT_ID
  type: string
- name: SP_BACKEND_CLIENT_ID
  type: string

stages:
- stage: BuildPortal
  displayName: Build portal stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: windows-latest
      
    steps:
    - task: NodeTool@0  
      inputs:
        versionSpec: '16.x'
      displayName: 'Install Node.js'

    - script: |
        npm install && npm run build      
      env:
        PORTAL_BACKEND_API_URL: ${{ parameters.apiUrl }}
        PORTAL_BACKEND_CLIENT_ID: ${{ parameters.SP_BACKEND_CLIENT_ID }}
        PORTAL_BACKEND_IDENTIFIER: ${{ parameters.backendIdentifier }}
        PORTAL_TENANT_ID: ${{ parameters.TENANT_ID }}
        PORTAL_CUSTOMER_NAME: ${{ parameters.COMPANY_NAME }}
      displayName: 'Prepare binaries'            
     
    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-portal.zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-portal.zip
      artifact: drop-portal
      
    - upload: $(System.DefaultWorkingDirectory)/contentTypes.ps1
      artifact: drop-portal-ps