parameters:
- name: environment
  type: string
- name: resourceGroupName
  type: string
- name: serviceConnection
  type: string
- name: storageAccountName
  type: string

stages:
- stage: Deployportal
  displayName: Deploy portal stage
  variables: 
  - group: ${{ parameters.environment }}
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: ${{ parameters.environment }}
    pool: 
      vmImage: 'windows-latest'
    strategy:
      runOnce:
        deploy:
          steps:

          - task: ExtractFiles@1
            inputs:
              archiveFilePatterns: '$(Pipeline.Workspace)/drop-portal/$(Build.BuildId)-portal.zip'
              destinationFolder: '$(Pipeline.Workspace)/drop-portal/portalextracted'
              cleanDestinationFolder: true
              overwriteExistingFiles: false

          - task: AzureFileCopy@3
            inputs:
              SourcePath: '$(Pipeline.Workspace)/drop-portal/portalextracted/'
              azureSubscription: ${{ parameters.serviceConnection }}
              Destination: 'AzureBlob'
              storage: ${{ parameters.storageAccountName }}
              ContainerName: '$web'

          - task: AzurePowerShell@5
            displayName: Get StorageAccountKey
            env: 
              RESOURCE_GROUP_NAME: '$(resourceGroupName)'
              STORAGE_ACCOUNT_NAME:  '$(storageAccountName)'
            inputs:
              azureSubscription: ${{ parameters.serviceConnection }}
              azurePowerShellVersion: LatestVersion
              ScriptType: 'InlineScript'
              Inline: |
                Write-Host "SOF Jiihaa"
                Write-Host "$Env:PORTAL_STORAGE_KEY"
                Write-Host "$Env:PORTAL_STORAGE_ACCOUNT"
                Write-Host "$Env:SP_BACKEND_CLIENT_ID"
                Write-Host "$Env:storageAccountName"
                Write-Host "$Env:storageAccountKey"
                Write-Host "EOF Jiihaa"
                $value=(Get-AzStorageAccountKey -ResourceGroupName "rg-dof-dev-weu" -Name "stdofncdevweu1")[0].Value
                Write-Host "##vso[task.setvariable variable=storageAccountKey;]$value"
              pwsh: true

          - task: AzurePowerShell@5
            displayName: Set ContentTypes
            env:
              STORAGE_KEY: '$(storageAccountKey)'
            inputs:
              azureSubscription: ${{ parameters.serviceConnection }}
              ScriptType: 'FilePath'
              ScriptPath: '$(Pipeline.Workspace)/drop-portal-ps/contentTypes.ps1'              
              azurePowerShellVersion: 'LatestVersion'