parameters:
- name: environment
  type: string
- name: STORAGE_KEY
  type: string
- name: storageAccount
  type: string
- name: azureSubscription
  type: string

stages:
- stage: Deployportal
  displayName: Deploy portal stage
  
  jobs:
  - deployment: Deploy
    displayName: Deploy    
    environment: ${{ parameters.environment }}
    pool: 
      vmImage: 'windows-latest'
    strategy:
      runOnce:
        deploy:
          steps:

          - task: ExtractFiles@1
            inputs:
              archiveFilePatterns: '$(Pipeline.Workspace)/drop-portal/$(Build.BuildId)-portal.zip'
              destinationFolder: '$(Pipeline.Workspace)/drop-portal/portalextracted'
              cleanDestinationFolder: true
              overwriteExistingFiles: false

          - task: AzureFileCopy@3
            inputs:
              SourcePath: '$(Pipeline.Workspace)/drop-portal/portalextracted/'
              azureSubscription: ${{ parameters.azureSubscription }}
              Destination: 'AzureBlob'
              storage: ${{ parameters.storageAccount }}
              ContainerName: '$web'
        
          - task: AzurePowerShell@5
            env:
              STORAGE_KEY: ${{ parameters.STORAGE_KEY }}
            inputs:
              azureSubscription: ${{ parameters.azureSubscription }}
              ScriptType: 'FilePath'
              ScriptPath: '$(Pipeline.Workspace)/drop-portal-ps/contentTypes.ps1'                            
              azurePowerShellVersion: 'LatestVersion'