parameters:
- name: environment
  type: string
- name: resourceGroupName
  type: string
- name: serviceConnection
  type: string
- name: storageAccountName
  type: string

stages:
- stage: Deployportal
  displayName: Deploy portal stage
  variables: 
  - group: ${{ parameters.environment }}
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: ${{ parameters.environment }}
    pool: 
      vmImage: 'windows-latest'
    strategy:
      runOnce:
        deploy:
          steps:

          - task: ExtractFiles@1
            inputs:
              archiveFilePatterns: '$(Pipeline.Workspace)/drop-portal/$(Build.BuildId)-portal.zip'
              destinationFolder: '$(Pipeline.Workspace)/drop-portal/portalextracted'
              cleanDestinationFolder: true
              overwriteExistingFiles: false

          - task: AzurePowerShell@5
            displayName: 'Enable public network access'
            inputs:
              azureSubscription: ${{ parameters.serviceConnection }}
              azurePowerShellVersion: LatestVersion
              ScriptType: 'InlineScript'
              Inline: |
                $resourceGroupName = "${{ parameters.resourceGroupName }}"
                $storageAccountName = "${{ parameters.storageAccountName }}"
                Update-AzStorageAccountNetworkRuleSet -ResourceGroupName $resourceGroupName -Name $storageAccountName -DefaultAction Allow
              pwsh: true

          - task: AzureFileCopy@3
            inputs:
              SourcePath: '$(Pipeline.Workspace)/drop-portal/portalextracted/'
              azureSubscription: ${{ parameters.serviceConnection }}
              Destination: 'AzureBlob'
              storage: ${{ parameters.storageAccountName }}
              ContainerName: '$web'

          - task: AzurePowerShell@5
            displayName: Get StorageAccountKey
            env: 
              RESOURCE_GROUP_NAME: 'rg-dof-dev-weu'
              STORAGE_ACCOUNT_NAME:  'stdofncdevweu1'
            inputs:
              azureSubscription: ${{ parameters.serviceConnection }}
              azurePowerShellVersion: LatestVersion
              ScriptType: 'InlineScript'
              Inline: |
                $resourceGroupName = "${{ parameters.resourceGroupName }}"
                $storageAccountName = "${{ parameters.storageAccountName }}"
                Write-Host "SOF Jiihaa"
                Write-Host "Directly written PORTAL_STORAGE_KEY = $Env:PORTAL_STORAGE_KEY"
                Write-Host "Directly written PORTAL_STORAGE_ACCOUNT = $Env:PORTAL_STORAGE_ACCOUNT"
                Write-Host "Directly written SP_BACKEND_CLIENT_ID = $Env:SP_BACKEND_CLIENT_ID"
                Write-Host "Directly written $resourceGroupName = $(resourceGroupName)"
                Write-Host "Directly written $$resourceGroupName = $($resourceGroupName)"
                Write-Host "Directly written storageAccountName = $Env:storageAccountName"
                Write-Host "Mapped RESOURCE_GROUP_NAME = $env:RESOURCE_GROUP_NAME"
                Write-Host "Mapped STORAGE_ACCOUNT_NAME = $env:STORAGE_ACCOUNT_NAME"
                Write-Host "Inline resourceGroupName = $resourceGroupName"
                Write-Host "Inline storageAccountName = $storageAccountName"
                Write-Host "EOF Jiihaa"
                $value=(Get-AzStorageAccountKey -ResourceGroupName $resourceGroupName -Name $storageAccountName)[0].Value
                Write-Host "##vso[task.setvariable variable=storageAccountKey;]$value"
              pwsh: true

          - task: AzurePowerShell@5
            displayName: Set ContentTypes
            env:
              STORAGE_KEY: '$(storageAccountKey)'
            inputs:
              azureSubscription: ${{ parameters.serviceConnection }}
              ScriptType: 'FilePath'
              ScriptPath: '$(Pipeline.Workspace)/drop-portal-ps/contentTypes.ps1'              
              azurePowerShellVersion: 'LatestVersion'
          
          - task: AzurePowerShell@5
            displayName: 'Disable public network access'
            inputs:
              azureSubscription: ${{ parameters.serviceConnection }}
              azurePowerShellVersion: LatestVersion
              ScriptType: 'InlineScript'
              Inline: |
                $resourceGroupName = "${{ parameters.resourceGroupName }}"
                $storageAccountName = "${{ parameters.storageAccountName }}"
                Update-AzStorageAccountNetworkRuleSet -ResourceGroupName $resourceGroupName -Name $storageAccountName -DefaultAction Deny
              pwsh: true