trigger:
  branches:
    include:
    - dev
  paths:
    exclude:
    - Pipelines/*

variables:
- group: 'common'
- name: env
  ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
    value: prd
  ${{ else }}:
    value: dev

stages:
- template: build.yml
  parameters: 
    apiUrl: 'https://func-$(SOLUTION)-backend-$(COMPANY)-$(env)-weu.azurewebsites.net'
    backendIdentifier: 'api://$(SP_BACKEND_CLIENT_ID)'
    TENANT_ID: $(TENANT_ID)
    SP_BACKEND_CLIENT_ID: $(SP_BACKEND_CLIENT_ID)

- template: deploy.yml
  parameters: 
    environment: 'portal-dev'
    resourceGroupName: 'rg-$(SOLUTION)-$(env)-weu'
    serviceConnection: '$(SERVICE_CONNECTION_PREFIX)-$(env)'
    storageAccountName: 'st$(SOLUTION)$(COMPANY)$(env)weu1'