trigger:
  branches:
    include:
    - dev
  paths:
    exclude:
    - Pipelines/*

variables:
- group: 'common-dtst'
- name: env
  ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
    value: prd
  ${{ else }}:
    value: dev

stages:
- template: build.yml
  parameters: 
    apiUrl: 'https://func-$(SOLUTION_SHORT_NAME)-backend-$(COMPANY_SHORT_NAME)-$(env)-weu.azurewebsites.net'
    backendIdentifier: 'api://$(SP_BACKEND_CLIENT_ID)'
    COMPANY_NAME: $(COMPANY_FULL_NAME)
    TENANT_ID: $(TENANT_ID)
    SP_BACKEND_CLIENT_ID: $(SP_BACKEND_CLIENT_ID)

- template: deploy.yml
  parameters: 
    environment: 'portal-$(env)'
    resourceGroupName: 'rg-$(SOLUTION_SHORT_NAME)-$(env)-weu-001'
    serviceConnection: '$(SERVICE_CONNECTION_PREFIX)-$(env)'
    storageAccountName: 'st$(SOLUTION_SHORT_NAME)$(COMPANY_SHORT_NAME)$(env)weu1'