trigger:
  branches:
    include:
    - dev
  paths:
    exclude:
    - Pipelines/*

variables:
- group: 'common'
- group: 
  ${{ if eq(variables['Build.SourceBranchName'], 'production') }}:
    value: 'portal-prd'
  ${{ else }}:
    value: 'portal-dev'
- name: env
  ${{ if eq(variables['Build.SourceBranchName'], 'production') }}:
    value: prd
  ${{ else }}:
    value: dev

stages:
- template: build.yml
  parameters: 
    apiUrl: $(PORTAL_BACKEND_API_URL)
    backendIdentifier: $(PORTAL_BACKEND_IDENTIFIER)
    tenantId: $(PORTAL_TENANT_ID)
    clientId: $(PORTAL_BACKEND_CLIENT_ID)

- template: deploy.yml
  parameters: 
    STORAGE_KEY: $(PORTAL_STORAGE_KEY)
    storageAccount: $(PORTAL_STORAGE_ACCOUNT)
    environment: 'portal-$(env)'
    serviceConnection: '$(SERVICE_CONNECTION_PREFIX)-$(env)'