trigger: none

variables:
- group: 'ncdof-PortalVariables'

stages:
- template: ..\azure-portal-build-general.yml
  parameters: 
    API_URL: $(API_URL)
    BACKEND_IDENTIFIER: $(BACKEND_IDENTIFIER)
    TENANT_ID: $(TENANT_ID)
    CLIENT_ID: $(CLIENT_ID)

- template: ..\azure-portal-release-general.yml
  parameters: 
    STORAGE_KEY: $(STORAGE_KEY)
    STORAGE_ACCOUNT: $(STORAGE_ACCOUNT)
    environmentName: 'nc-dof-portal-development'
    azureSubscription: 'spn-devops-dof-development'