trigger:
- main
- production

variables:
- group: 'ncdof-PortalVariables'
- name: environment
  ${{ if eq(variables['Build.SourceBranchName'], 'production') }}:
    value: production
  ${{ else }}:
    value: development
- name: env
  ${{ if eq(variables['Build.SourceBranchName'], 'production') }}:
    value: prod
  ${{ else }}:
    value: dev

stages:
- template: build.yml
  parameters: 
    apiUrl: $(PORTAL_BACKEND_API_URL)
    backendIdentifier: $(PORTAL_BACKEND_IDENTIFIER)
    tenantId: $(PORTAL_TENANT_ID)
    clientId: $(PORTAL_BACKEND_CLIENT_ID)

- template: deploy.yml
  parameters: 
    STORAGE_KEY: $(PORTAL_STORAGE_KEY)
    storageAccount: $(PORTAL_STORAGE_ACCOUNT)
    environment: 'nc-dof-portal-$(environment)'
    azureSubscription: 'spn-devops-dof-$(environment)'