trigger:
- main
- production

variables:
- group: 'ncdof-PortalVariables'
- name: environment
  ${{ if eq(variables['Build.SourceBranchName'], 'production') }}:
    value: production
  ${{ else }}:
    value: development
- name: env
  ${{ if eq(variables['Build.SourceBranchName'], 'production') }}:
    value: prod
  ${{ else }}:
    value: dev

stages:
- template: build.yml
  parameters: 
    apiUrl: 'https://func-ncdof-backend-$(env)-weu.azurewebsites.net'
    backendIdentifier: 'api://3b65e541-04a8-4457-b27a-479cbb86e44b'
    tenantId: '647b4812-c4fd-4afe-864b-a854de083eeb'
    clientId: '3b65e541-04a8-4457-b27a-479cbb86e44b'

- template: deploy.yml
  parameters: 
    STORAGE_KEY: $(STORAGE_KEY)
    storageAccount: 'uincdofdevweu1'
    environment: 'nc-dof-portal-$(environment)'
    azureSubscription: 'spn-devops-dof-$(environment)'