trigger:
  branches: 
    include:
      - 'main'

pool:
    vmImage: 'ubuntu-latest'

variables:
- group: common

steps:
- checkout: self
  persistCredentials: true
- bash: |
    git remote add destination https://$(ORION_ADO_PAT)@$(ORION_ADO_GIT_URL)portal
    git fetch --unshallow origin '+refs/heads/*:refs/heads/*' --update-head-ok --tags
    git --no-pager branch -a -vv
    git tag
    git push destination --all -f --follow-tags
  displayName: 'Synchronize repository'